import type { Metadata } from 'next'
import './globals.css'
import { GlobalHeader } from '@/components/GlobalHeader'
import { GlobalFooter } from '@/components/GlobalFooter'
import { AntdRegistry } from '@ant-design/nextjs-registry'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='p-2 bg-gray-50'>
        <AntdRegistry>
          <GlobalHeader />
          <main>{children}</main>
          <GlobalFooter />
        </AntdRegistry>
      </body>
    </html>
  )
}
